// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLscWsLMQADWo-K8zraF-Cf_GGu6xjXCA',
    appId: '1:599362776939:android:801284b04bf1a36845262e',
    messagingSenderId: '599362776939',
    projectId: 'tt-meet-4051b',
    storageBucket: 'tt-meet-4051b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK1HpqGwMOtQqBl7oSNANka7GhTzW6w3k',
    appId: '1:599362776939:ios:8ac3412761ddb75345262e',
    messagingSenderId: '599362776939',
    projectId: 'tt-meet-4051b',
    storageBucket: 'tt-meet-4051b.appspot.com',
    androidClientId: '599362776939-c94j2eto34dm6cearh28mb73rtakm1tg.apps.googleusercontent.com',
    iosClientId: '599362776939-8cqp4g9mqsjle20s6geoo7257rtu8usk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ttMeet',
  );
}
